/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "NeonHologram"

include("plugin")
include("project:common")
include("project:common-impl")
include("project:common-nms")
include("project:common-nms-n120")
//include("project:common-display")